import pandas as pd
import numpy as np
array=np.array([22,56,78,99,90,80,78,87,87,80,90,94,83,83,85,65,99,50,79,89,77,98,96,94])
print(array)
arr=array.reshape(3,8)
print(arr)
print("Mean of the array is given below :--")
print(arr.mean())
print("mean for axis=1:---")
print(arr.mean(axis=1))
print("mean for axis=0:---")
print(arr.mean(axis=0))
print("Variance of the array is given below :--")
print(arr.var())
print("var for axis=1:---")
print(arr.var(axis=1))
print("var for axis=0:---")
print(arr.var(axis=0))
print("Standard Variance of the array is given below :--")
print(arr.std())
print("std for axis=1:---")
print(arr.std(axis=1))
print("std for axis=0:---")
print(arr.std(axis=0))